# Generated by Django 4.2.6 on 2023-12-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_seaborndataset"),
    ]

    operations = [
        migrations.AddField(
            model_name="seaborndataset",
            name="data",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="seaborndataset",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
