# Generated by Django 4.2.6 on 2023-12-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_seaborndataset_data_alter_seaborndataset_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seaborndataset",
            name="data",
            field=models.JSONField(default=None),
        ),
    ]
